# Name:   roles/b_base_setup/tasks/begin.yaml
# Updated: 2021-10-11
#
# See roles/a_begin/defaults/main.yaml for the begin_roles_to_run list.
---

- name: Task-01(Begin) - Info about each computer in this play...
  debug:
    msg: |
      "         Role: a_begin/tasks/a_begin.yaml"
      "   Admin_User: {{ admin_user_name | default('Missing Admin_user_name') }}"
      "         Host: {{ ansible_facts.hostname | default('Missing Host Name') }}"
      " Distribution: {{ ansible_facts.distribution }}: {{ ansible_facts.distribution_major_version }}"

- name: Task-02(Begin) - do the next step in 'begin_roles_to_run'.
  include_role:
    name: "{{ begin_item }}"
  loop: "{{ a_begin_roles_to_run }}"
  loop_control:
    loop_var: begin_item

### END DBK