# Ansible/Code/inventories/hosts.yaml
---
all:
    hosts:
        laptop-zbook:
        # bootstrap_pi:
    children:
        pinkpoppy:
            hosts:
                pi-01-pp:
                # pi-02-pp:
                pi-03-pp:
                pi-04-pp:
                pi-05-pp:
                pi-06-pp:
                pi-07-pp:
                pi-08-pp:
                pi-09-pp:
                pi-10-pp:
                pi-11-pp:
                pi-13-pp:
                # pi-14-pp:
                # pi-19-pp:
            vars:
                gateway-router: 172.16.0.5
        floating:
            hosts:
                laptop-zbook:
                laptop-marcia:
        cluster_01:
            hosts:
                pi-12-pp:
                pi-15-pp:
                pi-16-pp:
                pi-17-pp:
                pi-18-pp:
        pis:
            hosts:
                pi-[01:19]-pp:
        others:
            hosts:
                alki-pp:
                # router-01-pp:
    #
    # The following vars are global
    vars:
        domain-name: pyhouse.org
        # following is so I ssh as briank and not as root (which will not work).
        ansible_ssh_user: briank
        admin_user_name: briank
        global123: 123
        vpn_zt-network: vault_vpn_network_key

### END DBK
