# Ansible/Code/inventories/hosts.yaml
---
all:
    vars:
        domain-name: pyhouse.org
        # following is so I ssh as briank and not as root (which will not work).
        ansible_ssh_user: briank
        admin_user_name: briank
        global123: 123
        vpn_zt-network: vault_vpn_network_key

    children:
        pinkpoppy:
            vars:
                gateway-router: 172.16.0.5
            children:
                unclustered:
                    hosts:
                        pi-01-pp:
                        pi-[03:11]-pp:
                        pi-13-pp:
                cluster_01:
                    hosts:
                        pi-12-pp:
                        pi-[15:18]-pp:
                    vars:
                        cluster-01-var: cv1-secret
                cluster_02:
                    vars:
                        cluster-02-var: cv2
                fixed:
                    hosts:
                        alki-pp:
                        laptop-hp:
                    vars:
                        fixed-var: 'fv'
        roving:
            hosts:
                laptop-marcia:
                laptop-zbook:
        cannontrail:
            hosts:
                camera-03-ct:
            vars:
                ctvar: ctv

### END DBK
