# Name:    roles/setup_hostname/tasks/hostname.yaml
# Updated: 2021-10-17
#
# Set up the computer's hostname
#
# Vars:
#   ansible_facts.hostname

---

- name: Task-01(Hostname)
  ansible.builtin.debug:
    msg: |
        'HostName: {{ ansible_facts.hostname }}
        'Ansible_host: (( ansible_hostname }}'

- name: Task-02(Hostname)-Debian
  ansible.builtin.package:
    name:       dbus
    state:      present
  when:         ansible_os_family == 'Debian'

- name: Task-03(Hostname) - Update the hostname (pt. 1) - hostname cmd
  ansible.builtin.hostname:
    name:       "{{ ansible_facts.hostname }}"

- name: Task-04(Hostname) - Update the hostname (pt. 2) - (/etc/hostname)
  ansible.builtin.copy:
    content:    "{{ ansible_facts.hostname }}{{'\n'}}"
    dest:       /etc/hostname
    owner:      root
    group:      root
    mode:       0644

- name: Task-05(Hostname) - Update the IPv4 hostname (pt. 3) - (/etc/hosts)
  ansible.builtin.lineinfile:
    dest:       /etc/hosts
    regexp:     "^127.0.1.1"
    line:       "127.0.1.1{{'\t'}}{{ ansible_facts.hostname }}{% if domain_name != '' %}{{'\t'}}{{ ansible_facts.hostname }}.{{ domain_name }}{% endif %}{{'\t'}}localhost"
    state:      present

- name: Task-06(Hostname) - Update the IPv6 hostname (pt. 4) - (/etc/hosts)
  ansible.builtin.lineinfile:
    dest:       /etc/hosts
    regexp:     "^::1"
    line:       "::1{{'\t\t'}}{{ ansible_facts.hostname }}{% if domain_name != '' %}{{'\t'}}{{ ansible_facts.hostname }}.{{ domain_name }}{% endif %}{{'\t'}}localhost ip6-localhost ip6-loopback"
    state:      present

  ### END DBK
