# Name:   roles/b_setup_adminuser/tasks/add_user.yaml
# Updated: 2021-10-18
#
# This task sets up the main admin user (briank)

---

- name: Task-01(AddUser)
  ansible.builtin.debug:
    msg:
      - '         Role: b_setup_adminuser/tasks/add_user.yaml'
      - '   Admin_User: {{ master_username | default("Missing Admin_user_name") }} '
      - '         Host: {{ ansible_facts.hostname | default("Missing Host Name") }}'
      - ' Distribution: {{ ansible_facts.distribution }} : {{ ansible_facts.distribution_major_version }}'
      - ' Id: {{ ansible_lsb.id }}'

- name: Task-02-Suse(AddUser) - Add Admin User
  ignore_errors:    yes
  user:
    name:           "{{ master_username }}"
    password:       "{{ admin_user_password }}"
    comment:        "{{ admin_user_full_name }}"
    shell:          /bin/bash
    groups:         "{{ admin_user_groups }}"
  when: ansible_lsb.id == 'Suse'

- name: Task-02-Raspbian(AddUser) - Add Admin User
  ignore_errors:    yes
  user:
    name:           "{{ master_username }}"
    password:       "{{ admin_user_password }}"
    comment:        "{{ admin_user_full_name }}"
    shell:          /bin/bash
    groups:         "{{ admin_user_groups }}"
  when: ansible_lsb.id == 'Raspbian'

- name: Task-02-Ubuntu(AddUser) - Add Admin User
  ignore_errors:    yes
  user:
    name:           "{{ master_username }}"
    password:       "{{ admin_user_password }}"
    comment:        "{{ admin_user_full_name }}"
    shell:          /bin/bash
    groups:         "{{ admin_user_groups }}"
  when: ansible_lsb.id == 'Ubuntu'


- name: Task-03(AddUser) - Create the sudoers.d file for admin user
  ignore_errors:    yes
  template:
    src:            ./sudoers.j2
    dest:           "/etc/sudoers.d/{{ master_username }}"
    owner:          root
    group:          root
    mode:           0600

- name: Task-04(AddUser) - Be sure admin user home dir ownership is OK
  ignore_errors:    yes
  ansible.builtin.file:
    name:           "/home/{{ master_username }}/"
    state:          directory
    owner:          "{{ master_username }}"
    group:          "{{ master_username }}"
    mode:           0755

- name: Task-05(AddUser) - Create bin dir for admin user
  ignore_errors:    yes
  ansible.builtin.file:
    name:           "/home/{{ master_username }}/bin"
    state:          directory
    owner:          "{{ master_username }}"
    group:          "{{ master_username }}"
    mode:           0755

- name: Task-06(AddUser) - Copy admin files to ~/bin
  ignore_errors:    yes
  copy:
    src:            "files/ModelDiscovery.sh"
    dest:           "/usr/local/bin"
    owner:          "{{ master_username }}"
    group:          "{{ master_username }}"
    mode:           0755

- name: Task-07(AddUser) - Create admin user .ssh dir
  ignore_errors:    yes
  ansible.builtin.file:
    name:           "/home/{{ master_username }}/.ssh"
    state:          directory
    owner:          "{{ master_username }}"
    group:          "{{ master_username }}"
    mode:           0700

- name: Task-08(AddUser) - Copy authorized_keys file to ~/.ssh
  copy:
    src:            "~/.ssh/authorized_keys"
    dest:           "/home/{{ master_username }}/.ssh"
    owner:          "{{ master_username }}"
    group:          "{{ master_username }}"
    mode:           0600

- name: Task-09(AddUser) - Copy id_rsa file to ~/.ssh
  copy:
    src:            "~/.ssh/id_rsa"
    dest:           "/home/{{ master_username }}/.ssh"
    owner:          "{{ master_username }}"
    group:          "{{ master_username }}"
    mode:           0600

### END DBK
