# Name:    roles/b_setup_avahi/tasks/avahi.yaml
# Updated: 2021-10-18
#
# The avahi package is used to advertise various communications to the server (ssh, vpn etc.)
# Add the avahi config files and restart the daemon

---

# We must have ssh in order for ansible to work so we advertise it here.
- name: Task-01(Avahi) - Add avahi service files
  ansible.builtin.copy:
    src:    ./ssh.service
    dest:   /etc/avahi/services/ssh.service
    owner:  root
    group:  root
    mode:   0644

# VPN adds a graphic way to talk to the server
- name: Task-02(Avahi) - Add avahi service files
  ansible.builtin.copy:
    src:    ./vnc.service
    dest:   /etc/avahi/services/vnc.service
    owner:  root
    group:  root
    mode:   0644

- name: Task-03(Avahi) - Enable avahi so it runs at boot time.
  systemd:
    name: avahi-daemon.service
    enabled: yes

### END DBK
