# Name:   roles/b_setup_adminuser/tasks/main.yaml
# Updated: 2021-10-18
#
# This task sets up the main admin user (briank)

---

# Allow this role to be skipped.
- name: Task-00(b_setup_avahi) Continue if enabled.
  include_tasks: avahi.yaml
  when: setup_avahi_role_enabled | bool

### END DBK
